json.errors do
    json.call(@user.errors)
end